# Tip for loading Data file.

In [ ]:
from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Replace 'path/to/your/csv/file.csv' with the actual path to your file in Google Drive
# For example, if your file is in a folder named 'my_data' in your Drive, the path would be '/content/drive/MyDrive/my_data/your_file.csv'
csv_path = '/content/drive/MyDrive/OPS Hackathon/Text Description Classification/synthetic_transactions_diverse.csv'

# Read the CSV file into a pandas DataFrame
try:
    df = pd.read_csv(csv_path)
    print("CSV file loaded successfully!")
    display(df.head()) # Display the first few rows of the DataFrame
except FileNotFoundError:
    print(f"Error: The file '{csv_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {e}")

Mounted at /content/drive
CSV file loaded successfully!

                                    text_description       category
0  Procured legal fee and contract review for €36...          Legal
1  Bought annual fee, membership for CAD$1,244.45...  Subscriptions
2  Spent onn charger, laptop, mouse for $602.94, ...    Electronics
3  Bought workshop and course fee for ₹286 and JP...       Training
4  Purchased diesel, petrol, gasoline (incl. gaso...           Fuel

In [6]:
from google.colab import drive
drive.flush_and_unmount()

OR

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/OneNishitRathod/Text-Description-Classification/refs/heads/Dev/synthetic_transactions_diverse.csv')

In [8]:
df.head()

                                    text_description       category
0  Procured legal fee and contract review for €36...          Legal
1  Bought annual fee, membership for CAD$1,244.45...  Subscriptions
2  Spent onn charger, laptop, mouse for $602.94, ...    Electronics
3  Bought workshop and course fee for ₹286 and JP...       Training
4  Purchased diesel, petrol, gasoline (incl. gaso...           Fuel

# Anatole Farber - Implementation

#### Write your observation: [Classification Tracker](https://docs.google.com/spreadsheets/d/1Pb3ryHwrBZLUZXm_x_-a0evyA-EOY4acN7AHCLOHrwE/edit?usp=sharing)

# Andrew Chen - Implementation

#### Write your observation: [Classification Tracker](https://docs.google.com/spreadsheets/d/1Pb3ryHwrBZLUZXm_x_-a0evyA-EOY4acN7AHCLOHrwE/edit?usp=sharing)

# Kenny Hoang - Implementation

#### Write your observation: [Classification Tracker](https://docs.google.com/spreadsheets/d/1Pb3ryHwrBZLUZXm_x_-a0evyA-EOY4acN7AHCLOHrwE/edit?usp=sharing)

# Lily S. Nickoshie - Implementation

#### Write your observation: [Classification Tracker](https://docs.google.com/spreadsheets/d/1Pb3ryHwrBZLUZXm_x_-a0evyA-EOY4acN7AHCLOHrwE/edit?usp=sharing)

# Nishit Rathod - Implementation

#### Write your observation: [Classification Tracker](https://docs.google.com/spreadsheets/d/1Pb3ryHwrBZLUZXm_x_-a0evyA-EOY4acN7AHCLOHrwE/edit?usp=sharing)

# Yanzhen Zhang - Implementation

#### Write your observation: [Classification Tracker](https://docs.google.com/spreadsheets/d/1Pb3ryHwrBZLUZXm_x_-a0evyA-EOY4acN7AHCLOHrwE/edit?usp=sharing)